### ISSUE TITLE
inplace_function copy-assignment fails

### ISSUE THREAD

**Issue by Quuxplusone** [WG21-SG14/SG14#111]
https://wandbox.org/permlink/nT7NOhnVm2JZopjh

    stdext::inplace_function<void(), 16> f;
    f = []() { puts("hello world"); };
    stdext::inplace_function<void(), 16> g;  // bonus: change 16 to 17 and it should still work
    g = f;  // ERROR!

Oddly, it *does* work for move-assignment!
I think the issue is some SFINAE on the wrong overload. Should be:

	template<typename Callable, class = typename std::enable_if<!std::is_lvalue_reference<Callable>::value>::type>
	inplace_function& operator=(Callable&& target)

That SFINAE looks sketchy to me anyway, but it seems to DTRT.

**Comment by carlcook** [comment]
Thanks! I'll look at this soon

**Comment by carlcook** [comment]
Yeah you are right. Here's the fix I think.

```
template<typename CallableT>
inplace_function& operator=(const CallableT& target) {

template<typename CallableT, class = typename std::enable_if<!std::is_lvalue_reference<CallableT>::value>::type>
inplace_function& operator=(CallableT&& target)
```

And indeed, without this change, copy assignment is failing, but move assignment still works.

**Comment by carlcook** [comment]
I still haven't committed this fix, but will do in a few days (I'm currently on leave and don't have workstation access...)

**Comment by carlcook** [comment]
Looks like Arthur made some changes, including this fix.
