### ISSUE TITLE
inplace_function implicit conversion chooses copy over move

### ISSUE THREAD

**Issue by Quuxplusone** [WG21-SG14/SG14#125]
This is a really unfortunate side-effect of a core language issue, IMNSHO; this week I have been actively working on trying to understand and diagnose the core issue. [CWG 1579](http://wg21.link/cwg1579) is related but its resolution left much to be desired.

Consider this program:

    using IPF20 = stdext::inplace_function<void(), 20>;
    using IPF40 = stdext::inplace_function<void(), 40>;
    static_assert(std::is_convertible<IPF20, IPF40>::value, "");

    IPF40 foo() {
        IPF20 f;
        return f;  // HERE
    }

What happens on the line marked "HERE"?  Naively, we would expect NRVO (copy elision). But that can't happen because IPF20 and IPF40 are not the same type. So, post-CWG1579, we would expect lvalue-to-rvalue conversion — we'd expect that the expression `f` is treated as an rvalue, and the wrapped functor is *moved* from `f` into the return slot. However, CWG1579 kicks in only for *constructors*; it does not kick in for `inplace_function`'s clever use of a [templated conversion operator](https://github.com/WG21-SG14/SG14/blob/98baf1a/SG14/inplace_function.h#L294-L312) to implement implicit conversions. So CWG1579 does *not* kick in, and what we actually get in this case is a *copy operation*.

SG14 could fix this by changing the implementation of implicit conversions for `inplace_function` to use converting constructors instead of conversion operators, but this strikes me as a library fix for a language bug. I am pessimistic but not fatalistic that we might actually be able to get a core language fix here. I'm opening this GitHub issue just to document the issue for posterity.

(I remember remarking on @Voultapher's unusual and clever use of conversion operators at the time. He convinced me that it was the Right Way to do it, and I still think it is, really. But I'm sad to see that it actually *does* have minor negative consequences due to this core language bug.)

**Comment by mattreecebentley** [comment]
Thanks for making me look up IMNSHO :)
Assumption of copy elision never works out well, in my experience. While it'd be nice to be able to rely on compilers and the language always doing the right thing, it's better to brute-force it if you always want the right outcome.
