### ISSUE TITLE
volatile inplace_function fails to compile

### ISSUE THREAD

**Issue by pthorn** [WG21-SG14/SG14#162]
If you declare a `volatile inplace_function<...>` variable you cannot call any or almost any methods on it, including `operator()()`, `bool operator()`, etc., presumably because volatile overloads for those are missing and the compiler refuses to use any overloads not marked volatile.

As you have probably guessed, I do bare metal programming and the variable I want to make volatile is accessed both from thread mode and an interrupt handler (for example, a timer interrupt calls a callback stored in a variable and sets it to empty). While I'm admittedly not entirely sure how necessary it is (it probably depends on many factors), this is a very common practice in embedded programming and I don't feel safe having to omit volatile. I see that there is effort being made to support embedded environments (e. g.  3b8145188ca52f1a21cacd7b284e32dbda7c4b09) which is a very good sign from my perspective. Would you be willing to consider adding volatile overloads?

**Comment by Quuxplusone** [comment]
I am 99.999% confident that you don't need this ability. As you say, "I'm admittedly not entirely sure how necessary it is ... I don't feel safe having to omit volatile" — but as engineers we should deal in actualities, not "feelings." For now, I recommend that you do

    #define Volatile

    Volatile inplace_function<int()> f;
    Volatile int x = f();

etc., and reopen this issue only if that solution produces incorrect or inefficient codegen for your program.

**Comment by phillipjohnston** [comment]
I use inplace function in multiple embedded programs as callbacks w/ the exact usage you describe. Volatile is not necessary.

**Comment by phillipjohnston** [comment]
I'm also not sure what exactly a volatile inplace_function would accomplish. You're telling the compiler not to perform read or write optimizations related to that variable. It makes sense for variables representing hardware registers, but not something like inplace_function. Also worth re-stating: **volatile != atomic**.

**Comment by TBBle** [comment]
Wouldn't `volatile` be appropriate if the function variable itself, e.g., `f`, was set in both the general code and the interrupt handler? The `volatile` would ensure the mainline code doesn't cache the function pointer's target between invocations if the interrupt handler has been run.

Perhaps there's rules for interrupt/signal handlers in C++ that mean this isn't necessary, but I haven't checked.

**Comment by Quuxplusone** [comment]
@TBBle: In your sample code, what prevents the signal handler from possibly running *during* the assignment `f = {}` in `do_thing`? If it ran in the middle of that assignment, it'd see `f` in a bad (half-assigned) state.

Real code that wants to do this kind of thing (and I'm not sure there is any) should probably store their callback in an `atomic_shared_ptr<inplace_function<Sig>> f` or an `atomic<inplace_function<Sig>*> f`, not a (non-atomic) `inplace_function<Sig> f` which is susceptible to tearing.

**Comment by TBBle** [comment]
Huh, yeah. For some reason I was thinking that signals only went off when control was handled to the kernel/libc using something like `open`. Weird...

Anyway, you're right. A totally-async signal does mean you need an atomic to be able to write to it at all.
