### ISSUE TITLE
Provide CMake & Conan installation support

### ISSUE THREAD

**Issue by liarokapisv** [WG21-SG14/SG14#167]
It would be very useful to have proper CMake installation support for the library. Then Conan support would also be trivial to add. Currently we have to fork the repo and write our own custom wrappers over SG14 or even copy the headers directly which is suboptimal since we then have to sync with the upstream version manually.

**Comment by p-groarke** [comment]
Hi @liarokapisv, thx for the PR. Does this install technique support `find_package`? If not, I can add full cmake install support.
