### ISSUE TITLE
Invalid platform toolset?

### ISSUE THREAD

**Issue by briterator** [WG21-SG14/SG14#19]
My copy of Visual Studio 2015  does not accept the toolchain specified in the vcxproj files. It states that the given toolset is not installed. If I change the toolset back to just v140 as it used to be instead of Visual Studio 2015 (v140) then it works properly.

**Comment by johnmcfarlane** [comment]
I'm not sure how, but I think this was probably me. I noticed this earlier
but have a bad install and am half way through reinstalling Windows now. If
it's not fixed by the time I'm back up, I'll take care of it. 😖

**Comment by WG21-SG14** [comment]
I'm away from my PC for another week.  Is one of you able to close this issue now?

Cheers,
Guy

**Comment by johnmcfarlane** [comment]
I'm not seeing this error in master any more. Still need to fix it in my
current branch though for some reason. BTW, any chance of being added to
the project?
Cheers
John
