### ISSUE TITLE
Shall unstable_remove take value by const reference instead of by value?

### ISSUE THREAD

**Issue by ilyapopov** [WG21-SG14/SG14#31]
Currently, `unstable_remove` algorithm takes argument `v` by value, which can involve unnecessary copying. Should it take the argument by const reference instead?

**Comment by johnmcfarlane** [comment]
I'd go with cref or possibly even universal reference if practical although
I notice that list::remove is a cref. I'm guessing it's a similar operation.

**Comment by schmaltzlicker** [comment]
Should probably take a const ref. There's no need for move so rvalue references aren't of notable value.

**Comment by schmaltzlicker** [comment]
Fixed in my fork.
