### ISSUE TITLE
Difficulty accessing SG14 from the web

### ISSUE THREAD

**Issue by johnmcfarlane** [WG21-SG14/SG14#50]
As demonstrated [here](https://groups.google.com/a/isocpp.org/forum/#!topic/sg14/ISPg-b0VeXU), SG14 is needs some changes in order to make it more accessible by more people. In particular, the three main audiences of the repository / organization are:

1. developers using Git to collaborate on code and documents;
2. the general public who may be curious about SG14 and wish to casually browse its associated documents and
3. ISO C++ activity including submitting papers as files in specific formats.

GitHub is naturally better suited to 1), OK for 2) and troublesome for 3). 

Suggested improvements include:
1. a general reorganization which ensures that anyone can clone the repo and find all the pertinent documents in a single place;
2. [GitHub Pages](https://pages.github.com/) to provide convenient URLs to browser-friendly document views and
3. Packaged builds of documents in HTML / PDF format for submission to the committee etc..

**Comment by hatcat** [comment]
I have just navigated to my proposal, which is a pdf, clicked on it to view it in GitHub and right-clicked on it to download it to the desktop.  Are we sure what the problem is?  Might it be more to do with consistency and clarity of naming?  Next time I make a submission I will go through the documents and see if I can come up with some process for this.

**Comment by johnmcfarlane** [comment]
PDFs are a proprietary binary format and as such, GitHub leaves them well alone. HTML files - on the other hand - are potentially viewed from any browser and even text editors. Thus, instead of zero ways to view them, there are at least two. I think that's where the confusion begins. 

If you've followed the thread I linked to above, you'll see it is not obvious how to download HTML files from a GitHub repo. For example, the URL <https://github.com/WG21-SG14/SG14/blob/master/Docs/Proposals/p0037.html> might lead you to think you're navigating to the HTML-format document in question. Not so. Click this link and you'll see a GitHub page *enclosing* the actual document. You can click the "Raw" button, then choose "Save As..." from your browser and then load the downloaded file from your file explorer (Finder etc.). That's a lot of steps to get an HTML file from a web browser!

**Comment by johnmcfarlane** [comment]
To try and avoid future problems such as those surrounding P0037's submission, and to demonstrate [GitHub pages](https://pages.github.com/), I've copied the paper to the same repo as the reference implementation. 

You can now view the paper in HTML format correctly in a browser through [this link](http://johnmcfarlane.github.io/fixed_point/docs/papers/p0037.html). You can see the same HTML file in the regular GitHub presentation style [here](https://github.com/johnmcfarlane/fixed_point/tree/master/docs/papers).

As far as I'm concerned this solves enough of the problems surrounding dissemination of documents via GitHub that I feel I can close this issue. I'd still be interested in fixed_point being a child rep of a WG21-SG14 org but at this point, that's not such a pressing matter. Cheers!
