### ISSUE TITLE
Please make me a WG21-SG14 organisation owner

### ISSUE THREAD

**Issue by TBBle** [WG21-SG14/SG14#84]
Sorry for putting this issue on the SG14 repo, I couldn't see a good place on github to otherwise post a message to @WG21-SG14/sg14, as suggested last July in https://groups.google.com/a/isocpp.org/d/msg/sg14/1yRloYFAkhs/Aq91OGjcBQAJ

Now that I have https://github.com/TBBle/SG14-comparing-virtual-functions functional, I have decided it makes more sense for the master copy (i.e. the one with github pages and an Issue Tracker) to be under the WG21-SG14 organisation.

According to https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/ this means I need "admin or owner" permissions with the receiving organisation.

If there's any concerns, I'm happy to subsequently be restricted to admin permissions on this specific repo once it's moved.

On the other hand, you may also consider this an offer to volunteer for organisation maintenance duties. ^_^

**Comment by johnmcfarlane** [comment]
I've invited you. LMK if you don't receive a notification.

**Comment by TBBle** [comment]
Thank you, appears to be working. https://github.com/WG21-SG14/SG14-comparing-virtual-functions now exists. I've left the SG14 in the repository title both to avoid having forks get weird, and so that outside WG21-SG14 context, it still makes sense.
