### ISSUE TITLE
Compilation fails under VS2015 community ed.

### ISSUE THREAD

**Issue by schmaltzlicker** [WG21-SG14/SG14#9]
The following test fails for me locally:

```cpp
 static_assert(safe_add<std::uint8_t, -4>(15, 13).get<int>() == 28, "sg14::safe_add test failed");
 ```
>C:\Dev\sg14\SG14\SG14\fixed_point.h(615): error C2338: mismatched safe_add parameters
>  C:\Dev\sg14\SG14\SG14\fixed_point.h(623): note: see reference to function template instantiation 'RESULT_TYPE sg14::_impl::add<RESULT_TYPE,REPR_TYPE,-4,int>(const HEAD &)' being compiled
>          with
>          [
>              RESULT_TYPE=output_type,
>              REPR_TYPE=uint8_t,
>              HEAD=int
>          ]
>  C:\Dev\sg14\SG14\SG14\fixed_point.h(632): note: see reference to function template instantiation 'RESULT_TYPE sg14::_impl::add<output_type,REPR_TYPE,-4,sg14::fixed_point<REPR_TYPE,-4>,int>(const HEAD &,const int &)' being compiled
>          with
>          [
>              RESULT_TYPE=output_type,
>              REPR_TYPE=uint8_t,
>              HEAD=sg14::fixed_point<uint8_t,-4>
>          ]
>  ..\..\..\SG14_test\fixed_point_test.cpp(223): note: see reference to function template instantiation 'sg14::fixed_point<REPR_TYPE,-3> sg14::safe_add<uint8_t,-4,int>(const sg14::fixed_point<REPR_TYPE,-4> &,const int &)' being compiled
>          with
>          [
>              REPR_TYPE=uint8_t
>          ]
>  ..\..\..\SG14_test\fixed_point_test.cpp(72): note: see reference to class template instantiation 'sg14::fixed_point<uint8_t,0>' being compiled

**Comment by johnmcfarlane** [comment]
Thanks. I'm not sure how I let that test through but it is invalid. It requires that the two arguments, 15 and 13 be implicitly converted to `fixed_point` objects. A pull request will be in shortly.

**Comment by johnmcfarlane** [comment]
Pull request: https://github.com/WG21-SG14/SG14/pull/11

**Comment by WG21-SG14** [comment]
schmaltzlicker, would you be able to verify John's fix for us please?

Cheers,
Guy

**Comment by schmaltzlicker** [comment]
Works for me
