### ISSUE TITLE
Stray VS2015 Intellisense database in repository

### ISSUE THREAD

**Issue by TBBle** [WG21-SG14/SG14#92]
@mattreecebentley, as far as I understand, [SG14.VC.db](https://github.com/WG21-SG14/SG14/blob/23dceac1aac09d324c532f207e4d1742d82ff869/VS2015/SG14/SG14.VC.db) should not have been committed in 23dceac1aac09d324c532f207e4d1742d82ff869?

Unless I've overlooked something, I'll put up a pull request to remove it.

**Comment by mattreecebentley** [comment]
Thanks, not sure how that got there. Fixed in last push.
